services:
- type: web
  name: s9tpepper.dev
  env: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production
